# Safe RL Human-Robot Shared Control - Production Configuration
# Optimized for safety, reliability, and performance in production

config_version: "1.0.0"
environment: "production"
created_at: "2025-08-26T10:00:00"
updated_at: "2025-08-26T10:00:00"

# Safety Configuration - Maximum safety for production
safety:
  emergency_stop_enabled: true
  watchdog_timeout_sec: 1.0  # Strict timeout for production safety
  safety_monitoring_rate_hz: 200.0  # High frequency monitoring
  force_limits_enabled: true
  position_limits_enabled: true
  velocity_limits_enabled: true
  redundant_checking: true  # Critical for production
  fail_safe_mode: "emergency_stop"  # Most conservative option
  
  # Conservative force limits for human safety
  max_force_x: 25.0
  max_force_y: 25.0
  max_force_z: 50.0
  max_torque_x: 10.0
  max_torque_y: 10.0
  max_torque_z: 5.0

# Hardware Configuration - Production hardware
hardware:
  robot_type: "exoskeleton"
  hardware_id: "prod_exo_001"
  communication_protocol: "ros"
  control_frequency_hz: 100.0  # High frequency for responsiveness
  
  num_joints: 6
  joint_names:
    - "shoulder_pitch"
    - "shoulder_roll"
    - "elbow"
    - "wrist_pitch"
    - "wrist_roll"
    - "gripper"
  
  # Conservative position limits for safety
  position_limits_min: [-1.2, -1.0, -1.5, -1.0, -1.5, 0.0]
  position_limits_max: [1.2, 1.0, 1.5, 1.0, 1.5, 0.8]
  velocity_limits: [1.5, 1.5, 2.0, 2.0, 2.0, 1.0]
  effort_limits: [80.0, 80.0, 60.0, 40.0, 40.0, 20.0]
  
  ros_namespace: "/safe_rl_production"
  serial_port: "/dev/ttyACM0"  # Production serial port
  serial_baudrate: 921600  # High baudrate for production
  can_interface: "can0"
  ethernet_address: "192.168.100.10"  # Production network
  ethernet_port: 8443  # Secure port

# Algorithm Configuration - Proven settings for production
algorithm:
  algorithm_type: "cpo"
  policy_network_type: "mlp"
  
  # Proven network architecture
  hidden_layers: [256, 256, 128]
  activation_function: "tanh"
  learning_rate: 0.0003  # Conservative learning rate
  
  # Production batch size
  batch_size: 2048
  num_epochs: 10
  gamma: 0.995  # Higher gamma for long-term safety
  gae_lambda: 0.95
  
  # Strict safety constraints
  cost_limit: 10.0  # Very conservative
  constraint_violation_penalty: 200.0  # High penalty
  safety_margin: 0.05  # Small margin for strict safety
  
  cpo_damping_coeff: 0.1
  cpo_max_kl: 0.005  # Conservative KL limit
  
  # Production episode settings
  max_episode_steps: 1000
  num_parallel_envs: 8
  total_training_steps: 2000000  # Full training

# User Preferences - Production defaults
user_preferences:
  user_id: "production_user"
  preferred_assistance_level: 0.6  # Moderate assistance
  preferred_control_mode: "shared"
  
  feedback_type: "haptic"  # Tactile feedback for production use
  feedback_intensity: 0.5  # Moderate intensity
  
  conservative_mode: true  # Always conservative in production
  custom_safety_limits: {}
  
  adaptation_enabled: true
  learning_from_demonstrations: true
  user_model_path: "/opt/safe_rl/models/production_user_model.pkl"

# Logging Configuration - Production appropriate
logging:
  log_level: "INFO"  # Standard production logging
  log_to_file: true
  log_to_console: false  # No console output in production
  log_file_path: "/var/log/safe_rl/production.log"
  max_log_file_size_mb: 200
  backup_count: 10
  
  # Performance monitoring enabled
  enable_performance_monitoring: true
  metrics_collection_rate_hz: 20.0
  
  # Selective logging for performance
  log_sensor_data: false  # Too much data for production
  log_control_commands: true
  log_safety_events: true
  log_user_interactions: true
  
  # Remote monitoring for production oversight
  enable_remote_monitoring: true
  monitoring_server_url: "https://monitoring.saferl.internal"
  monitoring_api_key: "${MONITORING_API_KEY}"  # From environment variable

# Environment-specific overrides
environment_overrides: {}