# Safe RL Human-Robot Shared Control - Staging Configuration
# Pre-production testing environment with production-like settings

config_version: "1.0.0"
environment: "staging"
created_at: "2025-08-26T10:00:00"
updated_at: "2025-08-26T10:00:00"

# Safety Configuration - Production-like but slightly more permissive
safety:
  emergency_stop_enabled: true
  watchdog_timeout_sec: 1.5  # Slightly more permissive than production
  safety_monitoring_rate_hz: 150.0  # High but not maximum
  force_limits_enabled: true
  position_limits_enabled: true
  velocity_limits_enabled: true
  redundant_checking: true
  fail_safe_mode: "emergency_stop"
  
  # Slightly higher limits than production for testing
  max_force_x: 35.0
  max_force_y: 35.0
  max_force_z: 70.0
  max_torque_x: 15.0
  max_torque_y: 15.0
  max_torque_z: 8.0

# Hardware Configuration - Staging hardware setup
hardware:
  robot_type: "exoskeleton"
  hardware_id: "staging_exo_001"
  communication_protocol: "ros"
  control_frequency_hz: 100.0
  
  num_joints: 6
  joint_names:
    - "shoulder_pitch"
    - "shoulder_roll"
    - "elbow"
    - "wrist_pitch"
    - "wrist_roll"
    - "gripper"
  
  # Staging position limits - between dev and production
  position_limits_min: [-1.4, -1.2, -1.6, -1.2, -1.6, -0.1]
  position_limits_max: [1.4, 1.2, 1.6, 1.2, 1.6, 0.9]
  velocity_limits: [2.0, 2.0, 2.5, 2.5, 2.5, 1.2]
  effort_limits: [100.0, 100.0, 80.0, 60.0, 60.0, 30.0]
  
  ros_namespace: "/safe_rl_staging"
  serial_port: "/dev/ttyACM0"
  serial_baudrate: 460800
  can_interface: "can0"
  ethernet_address: "192.168.50.10"  # Staging network
  ethernet_port: 8080

# Algorithm Configuration - Production settings for validation
algorithm:
  algorithm_type: "cpo"
  policy_network_type: "mlp"
  
  hidden_layers: [256, 256, 128]
  activation_function: "tanh"
  learning_rate: 0.0003
  
  batch_size: 2048
  num_epochs: 10
  gamma: 0.99
  gae_lambda: 0.95
  
  # Moderate safety constraints for staging testing
  cost_limit: 20.0
  constraint_violation_penalty: 150.0
  safety_margin: 0.1
  
  cpo_damping_coeff: 0.1
  cpo_max_kl: 0.01
  
  max_episode_steps: 1000
  num_parallel_envs: 8
  total_training_steps: 500000  # Reduced for staging

# User Preferences - Staging test user
user_preferences:
  user_id: "staging_tester"
  preferred_assistance_level: 0.5
  preferred_control_mode: "shared"
  
  feedback_type: "haptic"
  feedback_intensity: 0.6
  
  conservative_mode: true
  custom_safety_limits: {}
  
  adaptation_enabled: true
  learning_from_demonstrations: true
  user_model_path: "/opt/safe_rl/staging/models/staging_user_model.pkl"

# Logging Configuration - Detailed for staging validation
logging:
  log_level: "DEBUG"  # More verbose for staging testing
  log_to_file: true
  log_to_console: true  # Console output for staging
  log_file_path: "/var/log/safe_rl/staging.log"
  max_log_file_size_mb: 100
  backup_count: 5
  
  enable_performance_monitoring: true
  metrics_collection_rate_hz: 15.0
  
  # More detailed logging for staging validation
  log_sensor_data: true
  log_control_commands: true
  log_safety_events: true
  log_user_interactions: true
  
  # Test remote monitoring in staging
  enable_remote_monitoring: true
  monitoring_server_url: "https://staging-monitoring.saferl.internal"
  monitoring_api_key: "${STAGING_MONITORING_API_KEY}"

# Environment-specific overrides
environment_overrides: {}